version: "3.9"

services:
  api:
    image: blog
    container_name: blog
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
